### ISSUE TITLE
Moodle coding style not followed

### ISSUE THREAD

**Issue by mudrd8mz** [vnayan/moodle-admintool_bulkimportfiles#1]
The absence of PHP docs blocks, different indentation and other things like that make the plugin code harder to review. Please check https://docs.moodle.org/dev/Coding_style and try to follow it as much as possible.

**Comment by vnayan** [comment]
Hi,

This has been fixed.

**Comment by danmarsden** [comment]
I think there's still some room for improvement here - it might help to add travis-ci support to your plugin which would help you to get a report with the remaining issues:
more info here:
https://moodle.org/mod/forum/discuss.php?d=323384
