### ISSUE TITLE
Security issue: calling exec with user supplied data is bad.

### ISSUE THREAD

**Issue by danmarsden** [vnayan/moodle-admintool_bulkimportfiles#4]
https://github.com/vnayan/moodle-admintool_bulkimportfiles/blob/bc74963c4f762db1c152a5a3eacd0eed59f432e2/contentbulkupload.php#L95

temppath is populated with data from the csv right? - so it's possible someone could inject malicious code.

you need to sanitise the data much better before passing it to exec.

**Comment by vnayan** [comment]
This is fixed.
